version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - "> 7.12.1, < 7.13"
  - dependency-name: eslint
    versions:
    - "> 7.12.0, < 7.13"
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - "> 30.7.3, < 30.8"
  - dependency-name: eslint-plugin-prettier
    versions:
    - "> 3.3.0, < 3.4"
  - dependency-name: eslint-plugin-standard
    versions:
    - "> 4.0.1, < 4.1"
  - dependency-name: jest-environment-jsdom
    versions:
    - ">= 26.a, < 27"
  - dependency-name: kleur
    versions:
    - "> 4.0.0, < 4.1"
  - dependency-name: lint-staged
    versions:
    - "> 10.5.1, < 10.6"
  - dependency-name: prettier
    versions:
    - "> 2.2.0, < 2.3"
  - dependency-name: rollup
    versions:
    - "> 2.32.0, < 2.33"
  - dependency-name: rollup
    versions:
    - "> 2.33.2, < 2.34"
  - dependency-name: rollup
    versions:
    - "> 2.36.1, < 2.37"
  - dependency-name: rollup
    versions:
    - "> 2.38.0, < 2.39"
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - "> 5.2.0, < 5.3"
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - "> 11.0.0, < 11.1"
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - "> 11.1.0, < 11.2"
  - dependency-name: typescript
    versions:
    - "> 4.1.3, < 4.2"
  - dependency-name: "@types/prettier"
    versions:
    - "> 2.2.0, < 2.3"
  rebase-strategy: disabled
